#!/usr/bin/env bash
set -euo pipefail

# Creates a Turso database for Badloggen and writes credentials to .env.local.
# Prerequisites: turso CLI installed and logged in (`turso auth login`)
#
# Usage:
#   npm run db:setup-turso
#   npm run db:setup-turso -- --db-name badloggen-prod

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DB_NAME="${TURSO_DB_NAME:-badloggen}"
ENV_FILE="$ROOT/.env.local"
TURSO_BIN="${TURSO_BIN:-turso}"

while [[ $# -gt 0 ]]; do
  case $1 in
    --db-name)
      DB_NAME="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done

if ! command -v "$TURSO_BIN" >/dev/null 2>&1; then
  echo "Turso CLI not found."
  echo ""
  echo "Install it:"
  echo "  curl -sSfL https://get.tur.so/install.sh | bash"
  echo ""
  echo "Then log in:"
  echo "  turso auth login"
  exit 1
fi

if ! "$TURSO_BIN" auth whoami >/dev/null 2>&1; then
  echo "Not logged in to Turso. Run: turso auth login"
  exit 1
fi

echo "Creating Turso database '$DB_NAME' (if it does not exist)…"
"$TURSO_BIN" db create "$DB_NAME" --if-not-exists

DATABASE_URL="$("$TURSO_BIN" db show "$DB_NAME" --url)"
DATABASE_AUTH_TOKEN="$("$TURSO_BIN" db tokens create "$DB_NAME")"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-turso.sh — do not commit
DATABASE_URL=$DATABASE_URL
DATABASE_AUTH_TOKEN=$DATABASE_AUTH_TOKEN
EOF

echo ""
echo "Wrote $ENV_FILE"
echo ""
echo "Running migrations…"
cd "$ROOT"
export DATABASE_URL DATABASE_AUTH_TOKEN
node scripts/migrate-remote.mjs

echo ""
echo "=== Next steps for production (Vercel) ==="
echo ""
echo "Add these environment variables in Vercel → Project → Settings → Environment Variables:"
echo ""
echo "  DATABASE_URL=$DATABASE_URL"
echo "  DATABASE_AUTH_TOKEN=<token in .env.local>"
echo ""
echo "Or use the Turso integration in the Vercel marketplace — it sets these automatically."
echo ""
echo "For GitHub Actions (optional), add repository secrets:"
echo "  DATABASE_URL"
echo "  DATABASE_AUTH_TOKEN"
echo ""
